### ISSUE TITLE
Publish content-validation on npmjs

### ISSUE THREAD

**Issue by PhotoNomad0** [unfoldingWord/uw-content-validation#3]
Can use `https://github.com/unfoldingWord/datatable-translatable` as an example for configuration for npmjs.

**Comment by PhotoNomad0** [comment]
@RobH123 -  Some good news here.  It looks like you may be very close to being able to publish to npmjs.  I tried running `npm publish --dry-run`.  It looks like there are just some syntax errors to fix first:

```
ᐅ npm publish --dry-run

> content-validation@0.7.4 prepublishOnly .
> rm -fr ./dist & babel ./src --out-dir ./dist -s inline


The `corejs` option only has an effect when the `useBuiltIns` option is not `false`

SyntaxError: /Users/blm/Development/RCL/content-validation-rcl/src/demos/book-package-check/index.js: Only one default export allowed per module. (2:8)

  1 | export {default} from './checkBookPackage';
> 2 | export {default} from './BookPackageCheck';
    |         ^
  3 | 
    at Object._raise (/Users/blm/Development/RCL/content-validation-rcl/node_modules/@babel/parser/lib/index.js:764:17)
    at Object.raiseWithData (/Users/blm/Development/RCL/content-validation-rcl/node_modules/@babel/parser/lib/index.js:757:17)
    at Object.raise (/Users/blm/Development/RCL/content-validation-rcl/node_modules/@babel/parser/lib/index.js:751:17)
    at Object.checkDuplicateExports (/Users/blm/Development/RCL/content-validation-rcl/node_modules/@babel/parser/lib/index.js:12690:12)
    at Object.checkExport (/Users/blm/Development/RCL/content-validation-rcl/node_modules/@babel/parser/lib/index.js:12629:16)
    at Object.parseExport (/Users/blm/Development/RCL/content-validation-rcl/node_modules/@babel/parser/lib/index.js:12433:12)
    at Object.parseStatementContent (/Users/blm/Development/RCL/content-validation-rcl/node_modules/@babel/parser/lib/index.js:11437:27)
    at Object.parseStatement (/Users/blm/Development/RCL/content-validation-rcl/node_modules/@babel/parser/lib/index.js:11331:17)
    at Object.parseBlockOrModuleBlockBody (/Users/blm/Development/RCL/content-validation-rcl/node_modules/@babel/parser/lib/index.js:11913:25)
    at Object.parseBlockBody (/Users/blm/Development/RCL/content-validation-rcl/node_modules/@babel/parser/lib/index.js:11899:10) {
  loc: Position { line: 2, column: 8 },
  pos: 52,
  code: 'BABEL_PARSE_ERROR'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! content-validation@0.7.4 prepublishOnly: `rm -fr ./dist & babel ./src --out-dir ./dist -s inline`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the content-validation@0.7.4 prepublishOnly script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/blm/.npm/_logs/2020-08-17T14_05_33_919Z-debug.log
```
